### ISSUE TITLE
[Feature Request]: Alternate Samplers

### ISSUE THREAD

**Issue by patrickjonesdotca** [kabachuha/sd-webui-text2video#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I would like to use other samplers such as PLMS or Heun instead of DDIM

Is that possible?

### Proposed workflow

1. Select Sampler
2. Press Generate
3. Enjoy

**Comment by kabachuha** [comment]
Some compatible samplers added with #187
