### ISSUE TITLE
[Feature Request]: Add support to potat1 — edit: link provided

### ISSUE THREAD

**Issue by wandrzej** [kabachuha/sd-webui-text2video#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

There's a new model based on modelscope Potat1 https://huggingface.co/camenduru/potat1
I think it should be fairly straightforward to make it an option in the current SD WebUI extension. 

### Proposed workflow

1. Go to .... I guess to the HG page https://huggingface.co/camenduru/potat1

**Comment by kabachuha** [comment]
If you already have ModelScope running, just download the unet model from this link and replace ModelScope's file in its directory

https://huggingface.co/DREX-Institute/potat1.pth/blob/main/text2video_pytorch_model.pth

The text encoder conversion support is going to be soon too

**Comment by kabachuha** [comment]
Made progress on encoder conversion, but need someone to test

https://github.com/ExponentialML/Text-To-Video-Finetuning/pull/71

**Comment by kabachuha** [comment]
Here's the link to the fully converted weights https://huggingface.co/kabachuha/potat1-with-text-encoder-original-format

A test shows that it's working fine:

https://github.com/kabachuha/sd-webui-text2video/assets/14872007/c7be4cb9-d21e-4ef5-87f0-eeaff1ed1fd2
