### ISSUE TITLE
[Feature Request]: Hotswap modelscope models to support an easier workflow with zeroscope and the upscaling model

### ISSUE THREAD

**Issue by itspoidaman** [kabachuha/sd-webui-text2video#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Zeroscope V2 dropped, a model trained ontop of modelscope, but it comes in two parts. A model that you use for base generation, a model you use for upscaling. There's also the Potat1 model 

Requesting a feature that allows you to swap between the different modelscope custom models without having to rename/replace the file that it automatically points too, would also be nice if this feature dumped the currently loaded model from the memory pipeline 

### Proposed workflow

1. select which model you want to load with a drop down menu
2. it loads the model for you

**Comment by Yaiol** [comment]
I found a way to make things a bit easier, with renaming/replacing the files
Simply prepare two configuration files
Change the model_args variables ckpt_clip, ckpt_unet, ckpt_autoencoder

        "model_args": {
            "ckpt_clip": "zeroscope-v2-576x320-clip.bin",
            "ckpt_unet": "zeroscope-v2-576x320-unet.pth",
            "ckpt_autoencoder": "kabachucha-autoencoder.pth",
            "max_frames": 16,
            "tiny_gpu": 1
        },

And then create as much batch you need
copy zeroscope-v2-576x320.json configuration.json
