### ISSUE TITLE
[Feature Request]: model switcher

### ISSUE THREAD

**Issue by andzejsp** [kabachuha/sd-webui-text2video#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Would be nice to have a model selection in the drop down box, for multiple folders in models/modelscope/t2v/*

### Proposed workflow

1. Copy models in to separate folders under models/modelscope/t2v/* 
2. press refresh button next to model selection dropdown box
3. parse t2v/* folder for other folders and add them to list of selection

### Additional information

Aditional question, when rendering txt2vid with 24 frames i get good result thats close to prompt but whn i crank up the frames up to 125 i get snow or noise video, nothing close to prompt..  why is that and how to make longer videos?

**Comment by B34STW4RS** [comment]
You shouldn't lie about checking the exiting issues.

https://github.com/kabachuha/sd-webui-text2video/pull/186

For your follow on question:

https://github.com/kabachuha/sd-webui-text2video/discussions/164

**Comment by kabachuha** [comment]
Yeah, this issue may be closed by now
